### ISSUE TITLE
Improving and / or customising the commit message.

### ISSUE THREAD

**Issue by pbogdan** [knl/niv-updater-action#16]
It would be very nice if the commit message for update was improved a little bit. As a concrete example I recently added the action to one of my repositories and here's the first automated update:

https://github.com/pbogdan/nix-hie/pull/4

While the pull request itself looks very nice (I like how neat and informative it is) the subject of the commit message contains "## Motivation" which is not ideal. For me it would be nice if the subject of the commit was either the same as the title of the pull request or if possible if it could be customised.

**Comment by knl** [comment]
Hi @pbogdan thanks for reporting it. Seems some other people experienced the same problem, so it's now fixed in #18

**Comment by pbogdan** [comment]
Thank you very much for the quick fix!
