### ISSUE TITLE
Accept "sources-file" parameter

### ISSUE THREAD

**Issue by utdemir** [knl/niv-updater-action#23]
Thanks for creating this!

I have [a project](https://github.com/utdemir/hs-nix-template/) where `nix/sources.json` file is not at the root of the repository. It would be great if this action supported Niv's `--sources-file` option so I could point that to my sources.json.

**Comment by knl** [comment]
@utdemir Thanks for reporting this. I think I fixed it in #24. Sorry for a late response, I never got a notification from GitHub :(
