### ISSUE TITLE
Strip mentions from the pull request message

### ISSUE THREAD

**Issue by utdemir** [knl/niv-updater-action#26]
First, thanks for creating `niv-updater-action`, it is very convenient.

I have `niv-updater-action` running on my dotfiles repository, sending PR's every week. `nixpkgs` is one of the dependencies. 

Turns out, the nixpkgs commit messages tend to include references to issues/pr's on nixpkgs repository, for example:

![2020-05-23-162315_584x175_scrot](https://user-images.githubusercontent.com/928084/82721512-ca2a5c00-9d11-11ea-945c-509748cad41b.png)

This means that every time niv-updater-action sends a PR my repository, GitHub will mention that PR in the mentioned issue; but most of the times, it'll be a nuisance on nixpkgs. It looks like this is already happening on the wild:

From: https://github.com/NixOS/nixpkgs/pull/76994 (I know that I'm adding yet another mention here)
![2020-05-23-162557_728x501_scrot](https://user-images.githubusercontent.com/928084/82721548-1d041380-9d12-11ea-8087-64528f7d5d74.png)

In order to keep the nixpkgs issues clean, it would be great for `niv-updater-action` to somehow strip those mentions by default.

I'm not sure what would be the best way to do it, I guess we can either have a postprocessing step on the commit message removing/escaping the mention-causing phrases, or we can just wrap the each commit message in code blocks.

**Comment by Infinisil** [comment]
The same for usernames, e.g. see https://github.com/JJJollyjim/arewehackersyet/pull/6 where @deliciouslytyped is being pinged since a commit subjects mentions them

**Comment by nomeata** [comment]
I find these links _very_ useful (and actualy asked for the rewriting to make them possible – just leaving them as `#123` would link to the wrong repo).

Maybe there is a way to have a link that doesn't trigger Github’s backlinking?

**Comment by utdemir** [comment]
@nomeata 

> Is there a generic URL redirection service out there that the link could be wrapped in?

DuckDuckGo's one seems to work, try: http://r.duckduckgo.com/l/?uddg=https://github.com

**Comment by knl** [comment]
Hi all, I'll take a look at this issue and submit a PR tomorrow. Sorry for such a late response, I never got a notification from GitHub that there is an open issue :(

**Comment by knl** [comment]
@utdemir I created #29 to fix this issue, thanks for your patience. Would that work for you?

**Comment by knl** [comment]
> The same for usernames, e.g. see [JJJollyjim/arewehackersyet#6](https://github.com/JJJollyjim/arewehackersyet/pull/6) where @deliciouslytyped is being pinged since a commit subjects mentions them

@Infinisil I created https://github.com/knl/niv-updater-action/pull/31 to fix the issue you brought up.
