### ISSUE TITLE
PR description is not updated

### ISSUE THREAD

**Issue by knl** [knl/niv-updater-action#38]
Hmm, this doesn’t seem to be updating the PR description, does it?

_Originally posted by @nomeata in https://github.com/knl/niv-updater-action/issues/14#issuecomment-770778740_

**Comment by knl** [comment]
It should. These lines are responsible for such changes: https://github.com/knl/niv-updater-action/pull/37/files#diff-5aa8518f530033ed2efd0db4dd918d9144d524fde9dbd12d305bf0a40579bca4R472-R486.

I've noticed the update on some test PRs I have, but it was not obvious, because the updated commits come at the very end of the description. Do you see any errors?

**Comment by nomeata** [comment]
Let me double check: In https://github.com/dfinity/motoko/pull/2225 I see force-pushes, and indeed the force-pushed _commit_ is updated, but the PR description is unchanged. This is using `knl/niv-updater-action@v8`.

**Comment by knl** [comment]
Based on the offline discussion, the problem occurs because the action actually fails mid way. Up to that point, the commit has been pushed, but the description has not been updated. The reason why the action fails is this line:

```
pr_number="$(hub pr list -s "open" --head "$branch_name" -f "%I")"
```

It fails because `hub pr` works on the local checkout.
