### ISSUE TITLE
DuckDuckGo redirect now gives 400s

### ISSUE THREAD

**Issue by nmattia** [knl/niv-updater-action#49]
For instance: [http://r.duckduckgo.com/l/?uddg=https://google.com](http://r.duckduckgo.com/l/?uddg=https://google.com)

**Comment by knl** [comment]
Thanks for reporting this. It seems that duckduckgo stopped handling redirects, so this approach doesn't work anymore. I'll look into alternatives, but I don't think there are any.

I might take the route of implementing this service myself.
