### ISSUE TITLE
Need new release `@v11` (or `@v10.1`)

### ISSUE THREAD

**Issue by ggreif** [knl/niv-updater-action#56]
I am using `@v10`.

Looks like the installed `nix` is too old for `zstd` compression
https://github.com/dfinity/motoko/actions/runs/3773504725/jobs/6414998770

From the error log:
```
installing 'nix-2.3.16'
...
unknown compression method 'zstd'
```

I'd be happy to test if you do a pre-release :-)

**Comment by knl** [comment]
Thanks for reporting! I’ll be able to do a release in exactly a week, as I’m away from computer.

**Comment by ggreif** [comment]
> action to the current HEAD

Sure, but how do I accomplish that? `@HEAD`?

**Comment by knl** [comment]
You can use either @main or @FULLSHAVon meinem iPhone gesendetAm 03.01.2023 um 16:25 schrieb Gabor Greif ***@***.***>:﻿

action to the current HEAD

Sure, but how do I accomplish that? @HEAD?

**Comment by ggreif** [comment]
Looks like `knl/niv-updater-action@d1c37728deda061bda1d1459ad8193b887fa0eab` works as advertised! 👏

**Comment by knl** [comment]
Closing this issue as I just made a new release. Thanks @ggreif !
