### ISSUE TITLE
Fix issue references in PR messages

### ISSUE THREAD

**Issue by nomeata** [knl/niv-updater-action#8]
The PR message includes the log of the upstream repo, which is great! But if the upstream repo references PRs or issues (#123), then Github will render them pointing to the wrong repo.

I suggest to wrap the commit message in \` (easy solution). Or change the output and prepend the issue with the repo (`knl/niv-updater-action#3`) so that Github renders them correctly.

(Probably hard to to completely correct.)

**Comment by nomeata** [comment]
(I guess ideally this would be functionality built into `niv`, and not this action, so that I can create nice commit messages even when using `niv upgrade` locally.)

**Comment by knl** [comment]
Thanks for reporting the issue @nomeata ! Will see what I can do about it.
